version: 1
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000â€¬
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
  protocolLibThreads: -1
world:
  - worlds:
      - world
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
      - emerald_ore
      - diamond_ore
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - redstone_ore
      - stone
      - clay
    randomBlocks:
      air: 45
      clay: 1
      coal_ore: 1
      cobblestone: 1
      diamond_ore: 25
      emerald_ore: 10
      gold_ore: 5
      iron_ore: 5
      lapis_ore: 1
      mossy_cobblestone: 1
      obsidian: 1
      redstone_ore: 1
      stone: 1
      tnt: 1
  - worlds:
      - world_nether
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
      - netherrack
      - quartz_ore
    randomBlocks:
      netherrack: 1
      quartz_ore: 1
  - worlds:
      - world_the_end
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
    randomBlocks:
      end_stone: 1
      end_bricks: 1
      bedrock: 1
      obsidian: 1
      purpur_block: 1

proximity:
  - worlds:
      - world
    enabled: true
    distance: 16
    useFastGazeCheck: false
    defaults:
      y: 0
      above: true
      useBlockBelow: true
    hiddenBlocks:
      diamond_ore: {}
      emerald_ore: {}
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
    randomBlocks:
      stone: 1
  - worlds:
      - world_nether
    enabled: true
    distance: 16
    useFastGazeCheck: false
    defaults:
      y: 0
      above: true
      useBlockBelow: true
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
    randomBlocks:
      netherrack: 4
      quartz_ore: 1
  - worlds:
      - world_the_end
    enabled: true
    distance: 16
    useFastGazeCheck: false
    defaults:
      y: 0
      above: true
      useBlockBelow: true
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
    randomBlocks:
      end_stone: 1
