version: 1
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000â€¬
  maximumSize: 4096
  expireAfterAccess: 30000
world:
  - worlds:
      - world
    enabled: true
    darknessBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - emerald_ore
      - diamond_ore
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - redstone_ore
      - stone
      - clay
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - silver_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
    randomBlocks:
      air: 45
      clay: 1
      coal_ore: 1
      cobblestone: 1
      diamond_ore: 25
      emerald_ore: 10
      gold_ore: 5
      iron_ore: 5
      lapis_ore: 1
      mossy_cobblestone: 1
      obsidian: 1
      redstone_ore: 1
      stone: 1
      tnt: 1
  - worlds:
      - world_nether
    enabled: true
    darknessBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - netherrack
      - quartz_ore
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - silver_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
    randomBlocks:
      netherrack: 1
      quartz_ore: 1
  - worlds:
      - world_the_end
    enabled: true
    darknessBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - mob_spawner
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - silver_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
    randomBlocks:
      end_stone: 1
      end_bricks: 1
      bedrock: 1
      obsidian: 1
      purpur_block: 1

proximity:
  - worlds:
      - world
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      diamond_ore: {}
      emerald_ore: {}
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      silver_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
    randomBlocks:
      stone: 1
  - worlds:
      - world_nether
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      silver_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
    randomBlocks:
      netherrack: 4
      quartz_ore: 1
  - worlds:
      - world_the_end
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      mob_spawner: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      silver_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
    randomBlocks:
      end_stone: 1
