name: Build

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package -pl orebfuscator-plugin -B --also-make "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
        mkdir dist
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: dist/
