name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package -pl orebfuscator-plugin -B --also-make -Drevision=$RELEASE_VERSION
        mkdir dist
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn -pl orebfuscator-api --also-make -Drevision=$RELEASE_VERSION --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
