name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package -pl orebfuscator-plugin -B --also-make -Dorebfuscator.version=$RELEASE_VERSION
        mkdir dist
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
